"""empty message

Revision ID: 14ba71e10ca3
Revises: 
Create Date: 2024-11-19 14:00:40.252552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba71e10ca3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('wpi_id', sa.String(length=9), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wpi_id')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('grad_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseSA',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['sa_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'sa_id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_num', sa.String(length=5), nullable=False),
    sa.Column('term', sa.String(length=5), nullable=False),
    sa.Column('max_SA', sa.Integer(), nullable=False),
    sa.Column('curr_SA', sa.Integer(), nullable=False),
    sa.Column('min_GPA', sa.Integer(), nullable=False),
    sa.Column('min_grade', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'section_num', 'term', name='uix_course_section_term')
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_instructor_id'), ['instructor_id'], unique=False)

    op.create_table('application',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=5), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'section_id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('min_GPA', sa.Float(), nullable=False),
    sa.Column('min_grade', sa.Float(), nullable=False),
    sa.Column('term', sa.String(length=5), nullable=False),
    sa.Column('SA_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('application')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_instructor_id'))
        batch_op.drop_index(batch_op.f('ix_section_course_id'))

    op.drop_table('section')
    op.drop_table('courseSA')
    op.drop_table('student')
    op.drop_table('instructor')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
